---
- name: Install Config Packages
  hosts: localhost

  tasks:
  - name: Install NPM
    become: true
    ansible.builtin.apt:
      name:
        - nodejs
        - npm
      state: latest

  - name: Install Pyright.
    become: true
    community.general.npm:
      name: pyright
      global: true
