---
- name: Install Config Packages
  hosts: localhost

  tasks:
  - name: Install NPM
    become: true
    ansible.builtin.apt:
      name:
        - nodejs
        - npm
        - unzip
      state: latest
