---
- name: Install Config Packages
  hosts: localhost

  tasks:
  - name: Install APT Packages
    become: true
    ansible.builtin.apt:
      name:
        - nodejs
        - npm
        - unzip
        - stow
        - tmux
        - terminator
        - ripgrep
        - xsel
        - xclip
        - i3
      state: latest

  - name: Install Snap Packages
    become: true
    community.general.snap:
      name: nvim
      classic: true

  - name: Install TPM
    ansible.builtin.git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: '~/.tmux/plugins/tpm'

  - name: Synchronize Udev Rules
    synchronize:
      src: ../files/rules/
      dest: /etc/udev/rules.d
      recursive: true

  - name: Reload Rules
    become: true
    command: udevadm control --reload-rules

  - name: Udev Trigger
    become: true
    command: udevadm trigger --subsystem-match=tty
