---
- name: Install Config Packages
  hosts: localhost

  tasks:
  - name: Install APT Packages
    become: true
    ansible.builtin.apt:
      name:
        - nodejs
        - npm
        - unzip
        - stow
        - tmux
        - terminator
        - ripgrep
        - xsel
        - xclip
        - i3
      state: latest

  - name: Install Snap Packages
    become: true
    community.general.snap:
      name: nvim
      classic: true

  - name: Install TPM
    ansible.builtin.git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: '~/.tmux/plugins/tpm'
